[package]
name = "rqbit"
version = "5.6.0"
authors = ["Igor Katson <igor.katson@gmail.com>"]
edition = "2021"
description = "A bittorrent command line client and server."
license = "Apache-2.0"
documentation = "https://github.com/ikatson/rqbit"
repository = "https://github.com/ikatson/rqbit"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["default-tls", "webui"]
openssl-vendored = ["openssl/vendored"]
tokio-console = ["console-subscriber", "tokio/tracing"]
webui = ["librqbit/webui"]
timed_existence = ["librqbit/timed_existence"]
default-tls = ["librqbit/default-tls"]
rust-tls = ["librqbit/rust-tls"]

[dependencies]
librqbit = { path = "../librqbit", default-features = false, version = "5.6.0" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
console-subscriber = { version = "0.2", optional = true }
anyhow = "1"
clap = { version = "~4.4", features = ["derive", "deprecated"] }
clap_complete = "~4.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
regex = "1"
futures = "0.3"
parse_duration = "2"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
size_format = "1"
bytes = "1.5.0"
openssl = { version = "0.10", features = ["vendored"], optional = true }

[dev-dependencies]
futures = { version = "0.3" }
