[package]
name = "rqbit"
version = "2.2.2"
authors = ["Igor Katson <igor.katson@gmail.com>"]
edition = "2018"
description = "A bittorrent command line client and server."
license = "Apache-2.0"
documentation = "https://github.com/ikatson/rqbit"
repository = "https://github.com/ikatson/rqbit"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sha1-system", "default-tls"]
sha1-system = ["librqbit/sha1-system"]
sha1-openssl = ["librqbit/sha1-openssl"]
sha1-rust = ["librqbit/sha1-rust"]
default-tls = ["librqbit/default-tls"]
rust-tls = ["librqbit/rust-tls"]

[dependencies]
librqbit = {path="../librqbit", default-features=false, version = "2.2.2"}
dht = {path="../dht", package="librqbit-dht", version="2.2.2"}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
anyhow = "1"
clap = {version = "4", features = ["derive", "deprecated"]}
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
regex = "1"
futures = "0.3"
parse_duration = "2"
parking_lot = {version = "0.12", features = ["deadlock_detection"]}
reqwest = "0.11"
serde = {version = "1", features=["derive"]}
serde_json = "1"
size_format = "1"

[dev-dependencies]
futures = {version = "0.3"}