[package]
name = "rqbit"
description = "A bittorent client"
version = "1.1.0"
authors = ["Igor Katson <igor.katson@gmail.com>"]
edition = "2018"

[features]
default = ["sha1-system", "default-tls"]
sha1-system = ["librqbit/sha1-system"]
sha1-openssl = ["librqbit/sha1-openssl"]
sha1-rust = ["librqbit/sha1-rust"]
default-tls = ["librqbit/default-tls"]
rust-tls = ["librqbit/rust-tls"]

[dependencies]
librqbit = {path="../librqbit", default-features=false}
dht = {path="../dht"}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
anyhow = "1"
clap = "3.0.0-beta.2"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1"
futures = "0.3"
parse_duration = "2"
size_format = "1"

[dev-dependencies]
futures = {version = "0.3"}